---
title: "R Notebook"
author: "Ankit Mithbavkar"
date: "'r Sys.Date()'"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
data <- read_csv("Bats_Balls_2025-10-02.csv") |> 
  filter(DistributionChannel == "anonymous" & Progress == "100") |>
  select(subject_id = ResponseId, 
         date = EndDate, 
         
         cost_pencil_control = `Pencil Control`,
         conf_pencil_control = `Conf. Pencil Control`,
         
         cost_magazine_standard = `Magazine Standard`,
         conf_magazine_standard = `Conf. Mag. Stand.`,
         cost_magazine_control = Magazine_Control,
         conf_magazine_control = `Conf. Mag. Control`,
         
         cost_pencil_standard = Pencil_Standard,
         conf_pencil_standard = `Conf. Pencil Stand.`,
         familiar = Q10)
```
```{r}
data_conf <- data |>
  select(subject_id, date, contains("conf"))

```

```{r}
data_cost <- data |>
  select(subject_id, date, contains("cost"))

cost_long <- data_cost |>
  pivot_longer(contains("cost")) |>
  separate(name, into= c("DV", "object", "item"), sep= "_") |>
  mutate(cost_clean = case_when(parse_number(value) < 1 ~ parse_number(value) * 100,
                                parse_number(value) >= 1 ~ parse_number(value))) |>
  filter(is.na(cost_clean) == FALSE)
cost_long
```
```{r}
cost_long |>
  group_by(item, cost_clean) |>
  summarise(n = n())
```

```{r}
 conf_long <- data_conf |>
  pivot_longer(contains("conf")) |>
  separate(name,
           into = c("DV", "object", "item"),
           sep = "_") |>
  mutate(confidence_clean = parse_number(value)) |>
  group_by(item) |>
  summarise(mean_confidence = mean(confidence_clean, na.rm = TRUE))
conf_long
```

```{r}
conf_long |>
  filter(is.na(confidence_clean) == FALSE) |>
  select(-object) |>
  pivot_wider(names_from = item, 
              values_from = confidence_clean)
  ggplot(aes(y = control, x = standard)) + 
  geom_point()
```

